#!/usr/bin/python

from mininet.net import Mininet
from mininet.node import Controller, RemoteController
from mininet.cli import CLI
from mininet.log import setLogLevel, info

def myNet():


    CONTROLLER_IP1='127.0.0.1'

    net = Mininet( topo=None, build=False)

    # Create nodes
    h1 = net.addHost( 'h1', mac='02:00:00:00:01:00', ip='192.168.0.1/24' )
    h2 = net.addHost( 'h2', mac='02:00:00:00:02:00', ip='192.168.0.2/24' )
    h3 = net.addHost( 'h3', mac='02:00:00:00:03:00', ip='192.168.0.3/24' )
    h4 = net.addHost( 'h4', mac='02:00:00:00:04:00', ip='192.168.0.4/24' )

    
    # Create switches
    s1 = net.addSwitch( 's1', listenPort=6634, mac='04:00:00:00:00:01' , dpid= "4000000000000001")

    print "*** Creating links"
    """
    net.addLink(s1, s2, 1, 1)   
    net.addLink(s1, s3, 2, 1)
    net.addLink(s2, s4, 2, 1)
    net.addLink(s3, s4, 2, 2)
    net.addLink(s3, s5, 3, 1)
    net.addLink(s4, s5, 3, 2)
    net.addLink(h1, s1, 1, 3)
    net.addLink(h2, s3, 1, 4)
    net.addLink(h3, s3, 1, 5)
    net.addLink(h4, s5, 1, 3)
    """
    net.addLink(s1, h1, addr1 = "02:00:00:00:00:01")   
    net.addLink(s1, h2, addr1 = "02:00:00:00:00:02")   
    net.addLink(s1, h3, addr1 = "02:00:00:00:00:03")   
    net.addLink(s1, h4, addr1 = "02:00:00:00:00:04")   

    # Add Controllers
    c0 = net.addController( 'c0', controller=RemoteController, ip=CONTROLLER_IP1, port=6633)


    net.build()

    # Connect each switch to a different controller
    s1.start( [c0] )

    #s1.cmdPrint('ovs-vsctl show')

    CLI( net )
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'debug' )
    myNet()
