#!/bin/sh
ovs-vsctl set-manager ptcp:6632
curl -X PUT -d '"tcp:127.0.0.1:6632"' http://localhost:8080/v1.0/conf/switches/0000000000000002/ovsdb_addr
ovs-vsctl --all destroy qos
ovs-vsctl --all destroy queue

#curl -X POST -d '{"port_name": "s2-eth1", "type": "linux-htb", "max_rate": "1200000", "queues": [{"max_rate":"200000","min_rate":"100000"},{"max_rate":"400000","min_rate":"300000"},{"max_rate":"600000","min_rate":"500000"}]}' http://localhost:8080/qos/queue/0000000000000002
